// Utility functions for the school schedule system
import { CONFIG } from './config.js';

// Get Hebrew day name from day letter
export function getDayName(dayLetter) {
    return CONFIG.DAY_NAMES[dayLetter] || dayLetter;
}

// Check if a course is a special course that doesn't sync
export function isSpecialCourse(courseName) {
    const specialCourses = [
        "ספרייה", 
        "ספריה", 
        "פרלמנט", 
        "פרלמנט/שעה דמוקרטית", 
        "שעת חיבורים", 
        "שעת ועדות"
    ];
    return specialCourses.includes(courseName);
}

// Check if a course creates conflicts (opposite of special courses)
export function courseCreatesConflicts(courseName) {
    return !isSpecialCourse(courseName);
}

// Create a unique key for course selection
export function createCourseKey(time, day) {
    return `${time}_${day}`;
}

// Parse course key back to time and day
export function parseCourseKey(key) {
    const [time, day] = key.split('_');
    return { time, day };
}

// Create course value string for select options
export function createCourseValue(course, variant, teacher) {
    return `${course}|${variant}|${teacher}`;
}

// Parse course value back to components
export function parseCourseValue(value) {
    const [course, variant, teacher] = value.split('|');
    return { course, variant, teacher };
}

// Variants generated by the app (rather than read from the data) carry this prefix.
// They exist to give every occurrence of a course its own identity - without them all
// 9 library slots would share one identity and clearing one would clear them all - but
// they are an internal key and must never be shown to the user.
export const SYNTHETIC_VARIANT_PREFIX = '~';

export function isSyntheticVariant(variant) {
    return typeof variant === 'string' && variant.startsWith(SYNTHETIC_VARIANT_PREFIX);
}

// Format course display name: real section number only, teacher only when known
export function formatCourseDisplay(course, variant, teacher) {
    const displayVariant = variant && !isSyntheticVariant(variant) ? ` (${variant})` : '';
    const displayTeacher = teacher ? ` - ${teacher}` : '';
    return `${course}${displayVariant}${displayTeacher}`;
}

// Validate time slot format
export function isValidTimeSlot(timeSlot) {
    return /^\d{2}:\d{2}-\d{2}:\d{2}$/.test(timeSlot);
}

// Validate day letter
export function isValidDayLetter(dayLetter) {
    return CONFIG.DAYS.includes(dayLetter);
}

// Validate grade level
export function isValidGradeLevel(gradeLevel) {
    return Object.keys(CONFIG.GRADE_LEVELS).includes(gradeLevel);
}

// Check if a teacher name is empty or undefined
export function hasValidTeacher(teacher) {
    return Boolean(teacher && teacher.trim() !== '');
}

// Create course object
export function createCourseObject(course, variant, teacher, isAutoSynced = false) {
    return {
        course: course,
        variant: variant,
        teacher: teacher,
        isAutoSynced: isAutoSynced
    };
}

// Calculate statistics from selected courses
export function calculateStats(selectedCourses) {
    const courses = Object.values(selectedCourses);
    const manualSelections = courses.filter(c => !c.isAutoSynced).length;
    const autoSynced = courses.filter(c => c.isAutoSynced).length;
    const uniqueCourses = new Set(courses.map(c => `${c.course}_${c.variant}`)).size;
    
    return {
        manualSelections,
        autoSynced,
        totalSlots: courses.length,
        uniqueCourses
    };
}

// Escape a value for safe interpolation into HTML (attribute or text).
// Hebrew course names use gershayim (") for abbreviations - e.g. חט"ב, תנ"ך -
// which would otherwise terminate a quoted HTML attribute early.
export function escapeHtml(value) {
    return String(value ?? '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

// Wrap a value as a quoted CSV field, doubling embedded quotes per RFC 4180
export function escapeCsvCell(value) {
    return `"${String(value ?? '').replace(/"/g, '""')}"`;
}

// Compare two course selections by identity: course + variant + teacher.
// That triple is what identifies a course everywhere in the app, so keep this the
// single definition - the copies of this check had already drifted apart.
export function isSameCourseSelection(a, b) {
    return Boolean(a && b &&
        a.course === b.course &&
        a.variant === b.variant &&
        a.teacher === b.teacher);
}
